# -*- coding: utf-8 -*-
"""Practice_Manali.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i2HVFlmvCgUNOVug8CB1wMOgB1nHFsav
"""

# Print a number entered by user
Number1 = int(input("Please enter a number : "))
print ('----------------')
print('The number is ',Number1)

# Addition two integer numbers
Number1 = int(input("Enter first number - "))
Number2 = int(input("Enter second number - "))
Number3 = Number1 + Number2
print ('----------------------')
print ('Addition of two numbers are ', Number3)

# Multiply two floating numbers
Number1 = float(input("Enter first number - "))
Number2 = float(input("Enter second number - "))
Number3 = Number1 * Number2
print ('----------------------')
print ('Multiplication of two numbers are ', Number3)

# Swapping two numbers with using 3rd number
Number1 = int(input("Enter first number - "))
Number2 = int(input("Enter second number - "))
Number3 = Number1
Number1 = Number2
Number2 = Number3

print ('--------------')
print ("First Number is ", Number1)
print ("Second Number is ", Number2)

